# The Docker image that will be used to build your app
image: node:lts

# Functions that should be executed before the build script is run
before_script:
  - npm i

# Pages section for building and deploying to GitLab Pages
pages:
  script:
    - npm run build

# Artifacts section specifying the path to store artifacts
artifacts:
  paths:
    - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH